server:
  port: 8082
 
spring:
 application:
   name: HOTEL-SERVICE
 datasource:
  url: jdbc:postgresql://localhost:5432/microservice
  username: postgres
  password: admin@123
 
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
 
 config:
    import: configserver:http://localhost:8085
  
#eureka:
# instance:
#   prefer-ip-address: true
# client:
#   fetch-registry: true  
#   register-with-eureka: true
#   service-url:
#     defaultZone: http://localhost:8761/eureka
okta:
  oauth2:
    issuer: https://dev-93986820.okta.com/oauth2/default
    audience: api://default
    